config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  root to: 'uploads#index'

  get "login" => 'sessions#new'
  post "login" => "sessions#create"
  delete "logout" => 'sessions#destroy'
  post "create_user" => "users#create"
  get 'signup' => "users#new"

end

app/models/user.rb
class User < ActiveRecord::Base

	attr_reader :get_path

	has_many :uploads, dependent: :destroy
	validates :name, presence: true, length: { minimum: 3, maximum: 50 }
	validates :email, presence: true, length: {	minimum: 6, maximum: 255 }

	validates_uniqueness_of :email, case_sensitive: false

	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

	after_create :create_folder
	before_save :downcase_email

	has_secure_password # this will validate password & confirmation

  def to_s
    name
  end
  
	def get_path
		"#{UPLOAD_PATH}#{id}/"
	end

private


	def downcase_email
		self.email.downcase!
	end

	def create_folder
		FileUtils.mkdir_p(get_path) unless File.directory?(get_path)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :already_logged_in!, only: :new
  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)

    if user.save
      session[:current_user_id] = user.id
      redirect_to root_url
    else
      flash[:danger] = user.errors.messages
      redirect_to signup_path
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.haml
.well.col-md-6.col-md-offset-3
  = form_for(@user, url: create_user_path(@user)) do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control", placeholder: "Minimum 6 & Maximum 50 characters"
    .form-group
      = f.label :email
      = f.email_field :email, class: "form-control", placeholder: "Valid email under 255 characters"
    .form-group
      = f.label :password
      = f.password_field :password, class: "form-control", placeholder: "Minimum 6 characters"
    .form-group
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: "form-control", placeholder: "Must match the above password"
    .form-group
      = f.submit "Sign Up", class: "btn btn-success"