config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  root to: 'uploads#index'

  get "login" => 'sessions#new'
  post "login" => "sessions#create"
  delete "logout" => 'sessions#destroy'
  post "create_user" => "users#create"
  get 'signup' => "users#new"

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_reader :get_path, :file_path
  belongs_to :user

  validates_presence_of :name, :user
  validates_format_of :name, with: /(\.|\/)(txt)\z/i

  after_create :create_folder
  before_destroy :del_folder

  def get_path
    "#{self.user.get_path}#{id}/"
  end

  def file_path
    get_path + name
  end
  
private

  def del_folder
    FileUtils.rm_rf(get_path) if File.directory?(get_path)
  end

  def create_folder
    FileUtils.mkdir_p(get_path) unless File.directory?(get_path)
  end

end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def index
    @files ||= Dir.entries("public/uploads").select {|f| !File.directory? f}
    # debugger
  end

  def create
    content = params[:content].read
    name = params[:content].original_filename

    uploaded_file = Upload.create!(content: content) 

    # Open a new stream and write to the file.
    File.open("#{Rails.root}/public/uploads/#{name}", "w") do |file| 
      begin
        file.write(content)
      ensure
        file.close
      end
    end
    flash[:success] = "The file was uploaded succesfully."
    redirect_to root_url
  end

  def file
    respond_to { |format| format.js {} }
    @file_name = params[:choose]
    File.open("#{Rails.root}/public/uploads/#{@file_name}", "r") do |file| 
      begin
        @file_contents = file.read
      ensure
        file.close
      end
    end
  end

  def command
    @file_name = params[:choose]
    cmd = params[:command] # Split space seperated into new array

    words = cmd.scan(/['|"][\w?\s*]+['|"]/) # grab the words for swapping
    @word1 = words[0][/(\w\s*)+/] if words[0]
    @word2 = words[1][/(\w\s*)+/] if words[1]
    cmd.gsub!(/['|"][\w?\s*]+['|"]/,"")

    @at_line = cmd.scan(/\d{1,}/)[0].to_i || 0 # grab the line number
    cmd.gsub!(/\d{1,}/, "")
    cmd.gsub!(/_/, "")

    cmd = cmd.split(/\s+/)

    cmd.each do |method|
      self.send("#{method}",
      {at_line: @at_line, word1: @word1, word2: @word2})
    end

    File.open("#{Rails.root}/public/uploads/#{@file_name}", "r") do |file| 
      begin
        @file_contents = file.read
      ensure
        file.close
      end
    end

  end

private

  # def i(word, at_line=0)
  def i(args = {})
    puts "i called"
    word = args[:word1] + "\n"
    at_line = args[:at_line]
    
    tempfile=File.open("file.tmp", 'w')
    f=File.new("#{Rails.root}/public/uploads/#{@file_name}")

    f.each_with_index do |line, index|

      if (index+1 == at_line)
        tempfile << word
        tempfile<<line
      else
        tempfile<<line
      end
    end
    tempfile << word if at_line == nil

    f.close
    tempfile.close

    FileUtils.mv("file.tmp", "#{Rails.root}/public/uploads/#{@file_name}")
  end

  # def r(word1, word2, at_line=0)
  def r(args = {})
    puts "r called"
    word1 = args[:word1]
    word2 = args[:word2]
    at_line = args[:at_line]

    tempfile=File.open("file.tmp", 'w')
    f=File.new("#{Rails.root}/public/uploads/#{@file_name}")

    if at_line == 0
      f.each { |line| tempfile << line.gsub(/#{word1}/i, word2) }
    else
      at_line = at_line
      f.each.with_index do |line, index|
        index+1 == at_line ? tempfile << line.gsub(/#{word1}/i, word2) : tempfile << line
      end
    end

    f.close
    tempfile.close

    FileUtils.mv("file.tmp", "#{Rails.root}/public/uploads/#{@file_name}")
  end

  # def rev(at_line=0)
  def rev(args = {})
    puts "rev called"
    at_line = args[:at_line]

    tempfile=File.open("file.tmp", 'w')
    f=File.new("#{Rails.root}/public/uploads/#{@file_name}")

    f.each_with_index do |line, index|
      if (index+1 == at_line)
        tempfile << line.reverse.gsub(/\n/,"") + "\n" # Remove the new line and and it to the end
      else
        tempfile << line
      end
    end

    f.close
    tempfile.close

    FileUtils.mv("file.tmp", "#{Rails.root}/public/uploads/#{@file_name}")
  end

  def s(args)
    puts "Inside S"
  end

  def d(args)
    at_line = args[:at_line]

    tempfile=File.open("file.tmp", 'w')
    f=File.new("#{Rails.root}/public/uploads/#{@file_name}")

    f.each_with_index do |line, index|
      unless (index+1 == at_line)
        tempfile << line
      end
    end

    f.close
    tempfile.close

    FileUtils.mv("file.tmp", "#{Rails.root}/public/uploads/#{@file_name}")
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  include UtilityFileMethods
  include FileMethods

  before_action :logged_in_users_only, except: :index
  before_action :read_uploaded_file, only: [:show, :destroy, :update]

  def index
    @files = current_user.uploads if current_user
  end

  def create
    content = params[:file].read
    name = params[:file].original_filename
    @upload = current_user.uploads.build(name: name)
    write_file(@upload.file_path, content) if @upload.save
  end

  def show
    @file_contents = read_file(@file.file_path)
  end

  def destroy
    @file.destroy # We need callbacks to run here
  end

  def update
    @file_path = @file.file_path
    cmd = params[:command]
    update_actions(cmd)

    @file_contents = read_file(@file_path)

    render :template => "uploads/show.js.erb", 
           :layout => false  

  end

  private

  def logged_in_users_only
    unless current_user
      flash[:danger] = "Log in to continue"
      redirect_to login_path
    end
  end

  def read_uploaded_file
    @file = current_user.uploads.find(params[:id])
  end

end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_footer.html.haml
#commandRow
  %input#commandInput.form-control{:placeholder => "Command: ⏎", :type => "text"}/
  .btn.btn-default{:onclick => "$('#fileUpload').click();"}
    %i.fa.fa-upload

app/views/uploads/command.js.erb
$('#result').empty();
<% @file_contents.split(/\n/).each do |f| %>
	$('#result').append('<li> <%= escape_javascript(f) %> </li>');
<% end %>
$('#result_file_name').html('<%= escape_javascript(@file_name) %>');

app/views/uploads/create.js.erb
$('#fileItems').append('<%= j(render "layouts/logged_in_content", file: @upload) %>');

app/views/uploads/destroy.js.erb
setTimeout(function() {
  $("#<%= @file.id %>").slideUp();
    setTimeout(function() {
      $("#<%= @file.id %>").remove();
    }, 300);
}, 300);

$('#resultTitle, #result').empty();

app/views/uploads/file.js.erb
$('#preview').empty();
<% @file_contents.split(/\n/).each do |f| %>
	$('#preview').append('<li> <%= escape_javascript(f) %> </li>');
<% end %>
$('#file_name').html('<%= escape_javascript(@file_name) %>');

app/views/uploads/index.html.haml
#progress
  .bar{:style => "width: 0%;"}
.row
  %h3#resultTitle
  #result.jumbotron
  %div
    = form_tag(uploads_path, method: :post, multipart: true) do
      = file_field_tag :file, multiple: true, id: "fileUpload"
  = render "footer"

app/views/uploads/show.js.erb
$('#result').empty();
$("#<%= @file.id %>").addClass('active').siblings().removeClass('active');
$("#resultTitle").html('<%= @file.name %>')
$('#result').append('<ol>')
<% @file_contents.each do |f| %>
$('#result > ol').append('<li><%= j(f.html_safe) %></li>')
<% end %>